version: "3.8"

services:
  # Database services
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bus-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - bus-network

  # Application services
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: fastapi run
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - bus-network

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A worker.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file: ".env"
    depends_on:
      - redis
      - postgres
      - app
    restart: unless-stopped
    networks:
      - bus-network

  # Celery beat scheduler
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A worker.celery.celery_app beat --scheduler redbeat.RedBeatScheduler --loglevel=info
    volumes:
      - .:/app
    env_file: ".env"
    depends_on:
      - redis
      - postgres
      - app
      - worker
    restart: unless-stopped
    networks:
      - bus-network

networks:
  bus-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:

